# Generated by Django 3.0.8 on 2020-08-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noraneko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply_Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無し', max_length=255, verbose_name='名前')),
                ('text', models.TextField(verbose_name='本文')),
                ('good', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='nekomodel',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nekomodel',
            name='name',
            field=models.CharField(default='名無し', max_length=255, verbose_name='名前'),
        ),
    ]
