# Generated by Django 2.2.15 on 2020-08-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noraneko', '0002_postcomment_replycomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nekopostmodel',
            name='good',
        ),
    ]
