# Generated by Django 2.2.15 on 2020-08-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noraneko', '0003_remove_nekopostmodel_good'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NekoPostModel',
            new_name='NekoPost',
        ),
    ]
